package es.upm.dit.isst.webLab.tests;

// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.HashMap;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
public class HistoryAndTransactionsTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
	System.setProperty( "webdriver.chrome.driver", "C:\\Users\\Usuario\\Documents\\4º\\2ºCuatrimestre\\ISST\\sd\\chromedriver.exe");
	driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void HistoryServletTest() {
    driver.get("http://localhost:8080/ISST2019/");
    driver.manage().window().setSize(new Dimension(1366, 728));
    driver.findElement(By.id("navbarDropdown")).click();
    driver.findElement(By.linkText("Activity")).click();
    driver.findElement(By.name("email")).click();
    {
      WebElement dropdown = driver.findElement(By.name("email"));
      dropdown.findElement(By.xpath("//option[. = 'Marta']")).click();
    }
    driver.findElement(By.name("email")).click();
    driver.findElement(By.id("navbarDropdown")).click();
    driver.findElement(By.linkText("Activity")).click();
    driver.findElement(By.id("navbarDropdown")).click();
    driver.findElement(By.linkText("Balance")).click();
    driver.findElement(By.id("navbarDropdown")).click();
    driver.findElement(By.linkText("Load Money")).click();
    driver.findElement(By.name("username")).click();
    driver.findElement(By.name("username")).sendKeys("Marta");
    driver.findElement(By.name("cardNumber")).click();
    driver.findElement(By.name("cardNumber")).sendKeys("1232123123");
    driver.findElement(By.cssSelector(".form-group:nth-child(1) .form-control:nth-child(1)")).sendKeys("05");
    driver.findElement(By.cssSelector(".input-group > .form-control:nth-child(2)")).sendKeys("21");
    driver.findElement(By.cssSelector(".col-sm-4 .form-control")).sendKeys("123");
    driver.findElement(By.name("amount")).sendKeys("98");
    driver.findElement(By.cssSelector(".card-body")).click();
    driver.findElement(By.cssSelector(".btn")).click();
    driver.findElement(By.id("navbarDropdown")).click();
    driver.findElement(By.linkText("Activity")).click();
    driver.findElement(By.id("navbarDropdown")).click();
    driver.findElement(By.linkText("Balance")).click();
    driver.findElement(By.linkText("Create Swap Request")).click();
    driver.findElement(By.name("amount")).click();
    driver.findElement(By.name("amount")).sendKeys("100");
    driver.findElement(By.id("sel1")).click();
    {
      WebElement dropdown = driver.findElement(By.id("sel1"));
      dropdown.findElement(By.xpath("//option[. = 'EUR']")).click();
    }
    driver.findElement(By.id("sel1")).click();
    driver.findElement(By.name("to")).click();
    {
      WebElement dropdown = driver.findElement(By.name("to"));
      dropdown.findElement(By.xpath("//option[. = 'CHF']")).click();
    }
    driver.findElement(By.name("to")).click();
    driver.findElement(By.cssSelector(".btn")).click();
    driver.findElement(By.cssSelector(".btn-block")).click();
    driver.findElement(By.name("email")).click();
    {
      WebElement dropdown = driver.findElement(By.name("email"));
      dropdown.findElement(By.xpath("//option[. = 'John']")).click();
    }
    driver.findElement(By.name("email")).click();
    driver.findElement(By.id("navbarDropdown")).click();
    driver.findElement(By.linkText("Activity")).click();
    driver.findElement(By.id("navbarDropdown")).click();
    driver.findElement(By.cssSelector(".dropdown-menu")).click();
    driver.findElement(By.id("navbarDropdown")).click();
    driver.findElement(By.linkText("Balance")).click();
    driver.findElement(By.id("navbarDropdown")).click();
    driver.findElement(By.linkText("Load Money")).click();
    driver.findElement(By.name("username")).click();
    driver.findElement(By.name("username")).sendKeys("jOHN");
    driver.findElement(By.cssSelector(".card-body")).click();
    driver.findElement(By.name("username")).sendKeys("J");
    driver.findElement(By.name("username")).click();
    driver.findElement(By.name("username")).sendKeys("John");
    driver.findElement(By.name("cardNumber")).click();
    driver.findElement(By.name("cardNumber")).sendKeys("123123123");
    driver.findElement(By.cssSelector(".form-group:nth-child(1) .form-control:nth-child(1)")).click();
    driver.findElement(By.cssSelector(".form-group:nth-child(1) .form-control:nth-child(1)")).sendKeys("05");
    driver.findElement(By.cssSelector(".input-group > .form-control:nth-child(2)")).sendKeys("21");
    driver.findElement(By.cssSelector(".col-sm-4 .form-control")).sendKeys("123");
    driver.findElement(By.name("amount")).sendKeys("80");
    driver.findElement(By.cssSelector(".btn")).click();
    driver.findElement(By.id("navbarDropdown")).click();
    driver.findElement(By.linkText("Activity")).click();
    driver.findElement(By.cssSelector(".navbar")).click();
    driver.findElement(By.id("navbarDropdown")).click();
    driver.findElement(By.linkText("Balance")).click();
    driver.findElement(By.linkText("Create Swap Request")).click();
    driver.findElement(By.name("amount")).sendKeys("1");
    driver.findElement(By.name("amount")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".justify-content-md-center:nth-child(1)"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).clickAndHold().perform();
    }
    {
      WebElement element = driver.findElement(By.cssSelector(".justify-content-md-center:nth-child(1)"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.cssSelector(".justify-content-md-center:nth-child(1)"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).release().perform();
    }
    driver.findElement(By.cssSelector(".justify-content-md-center:nth-child(1)")).click();
    driver.findElement(By.name("amount")).sendKeys("9100");
    driver.findElement(By.id("sel1")).click();
    {
      WebElement dropdown = driver.findElement(By.id("sel1"));
      dropdown.findElement(By.xpath("//option[. = 'GBP']")).click();
    }
    driver.findElement(By.id("sel1")).click();
    driver.findElement(By.name("to")).click();
    {
      WebElement dropdown = driver.findElement(By.name("to"));
      dropdown.findElement(By.xpath("//option[. = 'EUR']")).click();
    }
    driver.findElement(By.name("to")).click();
    driver.findElement(By.cssSelector(".btn")).click();
    driver.findElement(By.cssSelector(".btn-block")).click();
    driver.findElement(By.id("navbarDropdown")).click();
    driver.findElement(By.linkText("Activity")).click();
  }
}
